### PR TITLE
add refresh button (to re-apply filters)

### LINKED ISSUE #93: Add refresh button for date slider
Having to press enter in another research field is not very intuitive

### PR DESCRIPTION
**Pull request by prjemian**
- close #93

### CODE REVIEW

**Comment by prjemian** [comment]
refresh button is better placed in the date time range slider widget. to the right of the slider

**Comment by prjemian** [comment]
The refresh button image from moxy looks too small and blurry.  We'll work up a replacement.

**Comment by prjemian** [comment]
@rodolakis This is not ready for review but you said you could offer a different image for the refresh button.

**Comment by prjemian** [comment]
I believe the [image formats](https://doc.qt.io/qtforpython-5/PySide2/QtGui/QPixmap.html#reading-and-writing-image-files) for the [QPushButton](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QPushButton.html) are flexible.  See [this web search for xpm & bmp formats](https://duckduckgo.com/?q=xpm+or+bmp%3F&t=brave&ia=web).  Likely others are possible.

**Comment by prjemian** [comment]
@rodolakis All this PR needs is some new art for the refresh button.  As I look at it now, the current artwork suggest that the button might reset the date/time values and slider.  We want it to look like it will apply any and all the search terms in the panel.

**Comment by prjemian** [comment]
Since all that this PR needs is new artwork for the button, I moved that to a separate issue.  After this PR, I plan to work on #113 which must be done while no other branches exist (or there will be merge conflicts).

**Review by rodolakis — COMMENTED** [review]
done

**Pull request merged**
