### PR TITLE
Center column via role instead of delegate

### LINKED ISSUE #159: Center column text via role instead of delegate
While researching `Qt.BackgroundRole`, I found this list of common roles in the `QAbstractItemModel` class for different kinds of data and formatting:

`Qt.DisplayRole`: Data to be rendered as text.
`Qt.DecorationRole`: Data to be rendered as an icon.
`Qt.EditRole`: Data that can be edited.
`Qt.ToolTipRole`: Data to be displayed as a tooltip.
`Qt.StatusTipRole`: Data to be displayed in a status bar.
`Qt.WhatsThisRole`: Data that can be used to populate "What's This?" help messages.
`Qt.FontRole`: Font used to display data.
`Qt.TextAlignmentRole`: Alignment of the data.
`Qt.BackgroundRole`: Background color.
`Qt.ForegroundRole`: Foreground color (e.g., text color).
`Qt.CheckStateRole`: Check state (e.g., for checkable items).

We could use `Qt.TextAlignmentRole` instead of a delegate to center the "Scan ID" and "#points" in the table:

```
if role == Qt.TextAlignmentRole:
        if index.column() in [0,4]:
            return Qt.AlignCenter
        else:
            return Qt.AlignLeft
```

_Originally posted by @rodolakis in https://github.com/BCDA-APS/gemviz/issues/157#issuecomment-1706800894_

### PR DESCRIPTION
**Pull request by prjemian**
- close #159

### CODE REVIEW

**Comment by prjemian** [comment]
### before

before

### after

after

**Review by MDecarabas — APPROVED** [review]
LGTM!

**Review by rodolakis — APPROVED** [review]
LGTM

**Comment by prjemian** [comment]
Why is this failing now and not 14 hours ago?

```
2024-03-20T18:46:48.2330274Z ==================================== ERRORS ====================================
2024-03-20T18:46:48.2331181Z _______________ ERROR collecting gemviz/tests/test_chartview.py ________________
2024-03-20T18:46:48.2331725Z gemviz/tests/test_chartview.py:4: in <module>
2024-03-20T18:46:48.2332083Z     from .. import chartview
2024-03-20T18:46:48.2332381Z gemviz/chartview.py:14: in <module>
2024-03-20T18:46:48.2332708Z     import pyqtgraph as pg
2024-03-20T18:46:48.2333604Z ../../../micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/pyqtgraph/__init__.py:205: in <module>
2024-03-20T18:46:48.2334324Z     from .graphicsItems.AxisItem import *
2024-03-20T18:46:48.2335204Z ../../../micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/pyqtgraph/graphicsItems/AxisItem.py:11: in <module>
2024-03-20T18:46:48.2335999Z     from .GraphicsWidget import GraphicsWidget
2024-03-20T18:46:48.2336880Z ../../../micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/pyqtgraph/graphicsItems/GraphicsWidget.py:2: in <module>
2024-03-20T18:46:48.2337651Z     from .GraphicsItem import GraphicsItem
2024-03-20T18:46:48.2338493Z ../../../micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py:40: in <module>
2024-03-20T18:46:48.2339239Z     class GraphicsItem(object):
2024-03-20T18:46:48.2340077Z ../../../micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py:612: in GraphicsItem
2024-03-20T18:46:48.2340846Z     nodes: dict[str, Element]
2024-03-20T18:46:48.2341230Z E   TypeError: 'type' object is not subscriptable
2024-03-20T18:46:48.2341670Z =============================== warnings summary ===============================
2024-03-20T18:46:48.2342405Z ../../../micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/setuptools_scm/git.py:163
2024-03-20T18:46:48.2343329Z ../../../micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/setuptools_scm/git.py:163
2024-03-20T18:46:48.2344700Z   /home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.8/site-packages/setuptools_scm/git.py:163: UserWarning: "/home/runner/work/gemviz/gemviz" is shallow and may cause errors
2024-03-20T18:46:48.2345842Z     warnings.warn(f'"{wd.path}" is shallow and may cause errors')
2024-03-20T18:46:48.2346171Z 
2024-03-20T18:46:48.2346487Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2024-03-20T18:46:48.2347031Z =========================== short test summary info ============================
2024-03-20T18:46:48.2347682Z ERROR gemviz/tests/test_chartview.py - TypeError: 'type' object is not subscriptable
2024-03-20T18:46:48.2348609Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2024-03-20T18:46:48.2349125Z ========================= 2 warnings, 1 error in 0.48s =========================
```

**Comment by prjemian** [comment]
Py3.8 keeps failing in the CI, above.  Two weeks ago, it did not fail.  Looks like `pyqtgraph` was upgraded:

- two weeks ago ([passed](https://pipelinesghubeus8.actions.githubusercontent.com/SLCHXmlvhrpQGu7mYM13K9rXqlBPyfuh6JcCboNxrKOMyM8gZl/_apis/pipelines/1/runs/176/signedlogcontent/18?urlExpires=2024-03-20T20%3A54%3A06.2459732Z&urlSigningMethod=HMACV1&urlSignature=wIqKDg%2FQvvyloEaLB3nHBgOiTLvXoJ38vkN742I7w04%3D)): [0.13.3](https://github.com/pyqtgraph/pyqtgraph/releases/tag/pyqtgraph-0.13.3)
- today ([fails](https://productionresultssa4.blob.core.windows.net/actions-results/dd02b7ac-c1c3-4e34-8e1f-58a06313b159/workflow-job-run-67637d89-05a5-5580-3f91-e2b7aacf20ee/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-20T21%3A02%3A28Z&sig=S6XWZBPu6xb47rArQCpyFRX6DJmfFM22Z%2B4Vv2mtLeA%3D&sp=r&spr=https&sr=b&st=2024-03-20T20%3A52%3A23Z&sv=2021-12-02)): [0.13.4](https://github.com/pyqtgraph/pyqtgraph/releases/tag/pyqtgraph-0.13.4)

**Comment by prjemian** [comment]
The fail happens on `import pyqtgraph` and is not related to the code changes here (strictly Qt code).  I'll proceed with the merge.  Following [mdaviz](https://github.com/BCDA-APS/mdaviz/issues/55#issuecomment-1930874388), considering a refactor to matplotlib anyway, at least for line charts.

**Pull request merged**
