### PR TITLE
print() --> logger.debug (mostly)

### LINKED ISSUE #105: prefer logging to print
During initial development, various diagnostic information was `print()` to the console.  For a package, this console output should be suppressed.  Yet the diagnostics still have their value.  The Python [`logging`](https://docs.python.org/3/howto/logging.html) package is commonly used.  These diagnostics would be reported at the DEBUG level.

Convert existing `print()` arguments to use `logging` and possibly also report to the mainwindow's status bar, as appropriate.

### PR DESCRIPTION
**Pull request by prjemian**
- close #105

command-line help now shows:

```bash
$ gemviz -h
usage: gemviz [-h] [--log {critical,fatal,error,warn,warning,info,debug,notset}] [-v]

gemviz: Python Qt5 application to visualize Bluesky data from tiled server.

options:
  -h, --help            show this help message and exit
  --log {critical,fatal,error,warn,warning,info,debug,notset}
                        Provide logging level. Example '--log debug'. Default level: 'warning'
  -v, --version         show program's version number and exit
```

### CODE REVIEW

**Comment by prjemian** [comment]
The DEBUG level is very noisy.  Lots of Qt debug messages.  Here is the `info` level:

```bash
$ gemviz --log info
INFO:gemviz.app:Logging level: info
INFO:gemviz.mainwindow:Status: Application started ...
INFO:gemviz.mainwindow:Status: selected tiled server_uri='http://localhost:8020'
INFO:httpx:HTTP Request: GET http://localhost:8020/api/v1/ "HTTP/1.1 400 Bad Request"
INFO:gemviz.mainwindow:Status: Error for server_uri='http://localhost:8020': 400: Python Tiled client reports version 0.1.0a96. Version 0.1.0a104 or higher is needed to communicate with this Tiled server. http://localhost:8020/api/v1/
INFO:gemviz.mainwindow:Status: Application quitting ...
```

**Comment by prjemian** [comment]
Wow, even the `info` level is noisy, noting each `GET` from the server.  Here are just two lines:

```py
INFO:httpx:HTTP Request: GET http://localhost:8020/api/v1/search/training?filter%5Blookup%5D%5Bcondition%5D%5Bkey%5D=7a7700b3-7641-4bdc-ac2c-8dee241f6b41&filter%5Bcomparison%5D%5Bcondition%5D%5Boperator%5D=ge&filter%5Bcomparison%5D%5Bcondition%5D%5Boperator%5D=le&filter%5Bcomparison%5D%5Bcondition%5D%5Bkey%5D=time&filter%5Bcomparison%5D%5Bcondition%5D%5Bkey%5D=time&filter%5Bcomparison%5D%5Bcondition%5D%5Bvalue%5D=1618203600.0&filter%5Bcomparison%5D%5Bcondition%5D%5Bvalue%5D=1694025296.03235&sort=time "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET http://localhost:8020/api/v1/search/training?filter%5Blookup%5D%5Bcondition%5D%5Bkey%5D=7a7700b3-7641-4bdc-ac2c-8dee241f6b41&filter%5Bcomparison%5D%5Bcondition%5D%5Boperator%5D=ge&filter%5Bcomparison%5D%5Bcondition%5D%5Boperator%5D=le&filter%5Bcomparison%5D%5Bcondition%5D%5Bkey%5D=time&filter%5Bcomparison%5D%5Bcondition%5D%5Bkey%5D=time&filter%5Bcomparison%5D%5Bcondition%5D%5Bvalue%5D=1618203600.0&filter%5Bcomparison%5D%5Bcondition%5D%5Bvalue%5D=1694025296.03235&sort=time "HTTP/1.1 200 OK"
```

**Comment by prjemian** [comment]
With `--log info` and piping the output into a log file, this analysis:

```
(tiled) prjemian@arf:~/.../BCDA-APS/gemviz$ grep -v httpx /tmp/log.txt 
INFO:gemviz.app:Logging level: info
INFO:gemviz.mainwindow:Status: Application started ...
INFO:gemviz.mainwindow:Status: selected tiled server_uri='http://localhost:8020'
INFO:gemviz.mainwindow:Status: Selected catalog 'training'.
INFO:gemviz.mainwindow:Status: catalog 'training' is 'CatalogOfBlueskyRuns, v1'
INFO:gemviz.mainwindow:Status: None
INFO:gemviz.mainwindow:Status: 1-5 of 8857 runs
INFO:gemviz.mainwindow:Status: 1-5 of 8857 runs
INFO:gemviz.mainwindow:Status: Application quitting ...
(tiled) prjemian@arf:~/.../BCDA-APS/gemviz$ grep httpx /tmp/log.txt | wc -l
574
```

**Comment by prjemian** [comment]
@rodolakis Ready for review.

**Review by rodolakis — APPROVED** [review]
LGTM

**Pull request merged**
