### PR TITLE
allow run(s) on last date to appear in timeline

### LINKED ISSUE #94: last run start date not selectable from slider
The date time range slider steps by single day units.  The minimum is set to the day of the (start time of the) first run. The maximum is set to the day of the (start time of the) last run.  By truncating the hh:mm:ss value of the last run, any runs after midnight will not be selectable unless the text for the date is changed to include later times that day.

### PR DESCRIPTION
**Pull request by prjemian**
- close #94

### CODE REVIEW

**Comment by prjemian** [comment]
Still, there is a problem that the most recent run does not appear when the catalog is first opened.

**Comment by prjemian** [comment]
Related to PR #104

**Review by rodolakis — APPROVED** [review]
LGTM

**Review by olliviergassant — APPROVED** [review]
LGTM

**Review by rodolakis — COMMENTED** [review]
done

**Pull request merged**
