### PR TITLE
publish on PyPI

### LINKED ISSUE #101: register package with PyPI
register package with [PyPI](https://pypi.org/) for installation by `pip install gemviz`

### PR DESCRIPTION
**Pull request by prjemian**
- close #101

### CODE REVIEW

**Comment by prjemian** [comment]
```
         400 Invalid value for classifiers. Error: Classifiers ['Topic ::       
         Scientific/Engineering :: Biology', 'Topic :: Scientific/Engineering ::
         Geology'] are not valid classifiers.                                   
```

**Comment by prjemian** [comment]
Great!  Now we have a PyPI package: https://pypi.org/project/gemviz/

**Comment by prjemian** [comment]
Revert the work flow to _Triggers the workflow on push events but only for the main branch_.

**Comment by prjemian** [comment]
Mostly followed some AI advice to publish on PyPI.  Publishing workflow was copied from apstools.  So were the project badges on the README page (and modified for this repo).  Had to remove two unrecognized classifiers before PyPI would accept the new project.

**Review by rodolakis — APPROVED** [review]
Sounds good

**Pull request merged**
