### PR TITLE
Document the API

### LINKED ISSUE #215: start the API documentation
As-is, the docs are very thin.  Content only suitable for developers.  Start fleshing out the user-facing documentation and the API documentation.

Refer to the configuration in [apstools](https://github.com/BCDA-APS/apstools/blob/main/docs/source) & [bluesky_training](https://github.com/BCDA-APS/bluesky_training/tree/main/docs/source) as a start.

Particularly, get project parameters from the [configuration files](https://github.com/BCDA-APS/apstools/blob/main/docs/source/conf.py#L8-L38).

### PR DESCRIPTION
**Pull request by prjemian**
- close #215

### CODE REVIEW

**Comment by prjemian** [comment]
Add steps to the docs workflow so the built docs are downloadable for review.

**Comment by prjemian** [comment]
@rodolakis @MDecarabas - Ready for review. Download and examine the docs built (from the GitHub workflow): https://github.com/BCDA-APS/gemviz/actions/runs/8402982182

**Comment by prjemian** [comment]
I'm ready to merge this PR.

**Comment by rodolakis** [comment]
@prjemian I do not see how to open the documentation from the link you provided.

**Comment by prjemian** [comment]
Click the link and look for the download at the page bottom:
image

Once the download is complete, unzip, go into the folder, and open `index.html` in your local web browser.

**Comment by rodolakis** [comment]
It does not look like what you showed me on Friday:
image

**Comment by prjemian** [comment]
> It does not look like what you showed me on Friday

I agree.  I'll let you know when ready to download and view again.

**Comment by prjemian** [comment]
@rodolakis -- This page has the most recent downloadable: https://github.com/BCDA-APS/gemviz/actions/runs/8694842061

**Pull request merged**
