### PR TITLE
add workflows for publishing and unit testing

### LINKED ISSUE #99: continuous integration - apply routine unit testing, packaging, publishing
Begin regular execution of [unit tests](#86) and [documentation builds](#97) in GitHub Actions workflows.

### PR DESCRIPTION
**Pull request by prjemian**
- close #99

### CODE REVIEW

**Comment by prjemian** [comment]
https://www.timestamp-converter.com/

**Comment by prjemian** [comment]
https://github.com/The-Compiler/pytest-xvfb

**Comment by prjemian** [comment]
Compare with https://github.com/slaclab/pydm/blob/master/.github/workflows/run-tests.yml

**Review by rodolakis — APPROVED** [review]
Looks complicated to me, but ok!

**Pull request merged**
